# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20170701_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stat', models.CharField(max_length=200)),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.UserDetails')),
            ],
        ),
    ]
