# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='user_stat',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
