# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_auto_20170701_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='userdetails',
        ),
    ]
